[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
board_build.filesystem = littlefs

monitor_speed = 115200
lib_deps =
    https://github.com/me-no-dev/ESPAsyncWebServer.git
    bblanchon/ArduinoJson @ ^6.21.3